### ISSUE TITLE
incorrect placement of code

### ISSUE THREAD

**Issue by matrox471** [SpaceLock/spacelock#63]
this part won't work here.
it also need to be done in the controller.

https://github.com/SpaceLock/spacelock/blob/9d48921aa7f0323a0282add347b6c03130909df0/resources/views/Space/show.blade.php#L7

**Comment by matrox471** [comment]
also the currency is defined in the env as 'APP_CURRENCY', so maybe that would be an alternative ?

**Comment by Fiyorden** [comment]
Si on a le temps
